# 注册到 eureka server 配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8090
spring:
  application:
    name: gateway
  cloud:
    config:
      uri: http://localhost:8888/
      name: main
      profile: dev
      discovery:
        enabled: true
        service-id: config
      username: config-server
      password: 123456
  config:
    import: configserver:${spring.cloud.config.uri}
security:
  oauth2:
    client:
      client-id: user-client
      client-secret: user-secret-8888
      user-authorization-uri: http://localhost:8087/oauth/authorize
      access-token-uri: http://localhost:8087/oauth/token
    resource:
      id: user-client
      user-info-uri: user-info
    authorization:
      check-token-access: http://localhost:8087/oauth/check_token