# 注册到 eureka server 配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8763
spring:
  application:
    name: gateway
  cloud:
    config:
      uri: http://localhost:8762/
      name: main
      profile: dev
  config:
    import: configserver:${spring.cloud.config.uri}