# 注册到 eureka server 配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8090
spring:
  application:
    name: gateway
  cloud:
    config:
      uri: http://localhost:8888/
      name: main
      profile: dev
      discovery:
        enabled: true
        service-id: config
  config:
    import: configserver:${spring.cloud.config.uri}