# 注册到 eureka server 配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8087
spring:
  application:
    name: authority
  cloud:
    config:
      uri: http://127.0.0.1:8888/
      name: main
      profile: dev
      discovery:
        enabled: true
        service-id: config
      username: config-server
      password: 123456
  config:
    import: configserver:${spring.cloud.config.uri}